### ISSUE TITLE
Unable to find coop-astar.cpp

### ISSUE THREAD

**Issue by qinxianyuzi** [will-em/multi-agent-rollout#4]
Hi, When compiling with makefile, it prompts that coop-astar.cpp cannot be found. Please help me, thanks.

**Comment by will-em** [comment]
Hi,

Have you made sure that you are on the right branch? The branch `fulfillment-center` is the most up-to-date one and is the one used for the paper.

/William

**Comment by qinxianyuzi** [comment]
@will-em Yes, I'm pretty sure I use that branch. Some cpp files could not be found when compiling the test execution file.

**Comment by qinxianyuzi** [comment]
Also, in line 279 to line 281 in Environment.cpp, the size of swapPenalized is 100, and the tot_dim is 5404. When the for loop is used to assign values to swapPenalized, the subscript is out of bounds.

**Comment by will-em** [comment]
Hi again,

I see! The tests you are referring to was used during the implementation of coop astar and we didn't update them during our final refactoring of the codebase (and have no plans to), so the tests may not be usable at this point. 

Regarding the out of bound behavior in Environment.cpp, I've pushed a fix for it now. Thanks!

**Comment by qinxianyuzi** [comment]
Thanks for your reply. I have another question. In line 62 to line 77in Environment.cpp, if agentCount is not divisible by 4, then the size of m_agentPositions is larger than agentCount, which will cause some places to go out of bounds, such as line 16 in ControlPicker.cpp.

**Comment by will-em** [comment]
Hi,

You are correct, the number of agents is assumed to be a multiple of 4. Feel free to modify the constructor of the environment to your liking.
